// Kategori Rekap (kolom KET. di spreadsheet REKAP PJK KAPAL PERBULAN) — dropdown
export const KATEGORI_REKAP: string[] = [
  "DOCKING(BIAYA)",
  "DOCKING (INVESTASI)",
  "RUTIN",
  "INVESTASI DILUAR DOCKING",
];

// Mata Anggaran (dari sheet DATABASE) — bisa pilih >1
export const MATA_ANGGARAN: string[] = [
  "5010403003 (Kapal Ro-Ro)",
  "5010403100 (Permesinan & Kelistrikan Kapal)",
  "5010403009 (Akomodasi, Peralatan & Perlengkapan Kapal)",
  "5010317000 (Biaya Sertifikasi Alat Produksi Docking)",
  "5010302006 (Fumigasi)",
  "5010302004 (Mobilisasi Docking)",
  "1020604003 (Investasi Kapal Ro-Ro)",
  "1020604009 (Investasi Akomodasi, Peralatan & Perlengkapan Kapal)",
  "1020604010 (Investasi Permesinan dan Kelistrikan)",
];

// Vendor (DATABASE): nama PT/CV, direktur, pemeriksa (untuk BAPP fase 2)
export interface Vendor { nama: string; direktur: string; pemeriksa: string }
export const VENDOR_DB: Vendor[] = [
  { nama: "CV. ARGO JAYA MANDIRI", direktur: "FAHMI", pemeriksa: "IRSAN ANUGRAH" },
  { nama: "KOPKAR SUNDARI", direktur: "YOGO DWI SANTOSO", pemeriksa: "TRY ATMOJO" },
  { nama: "CV. SAMUDERA TEKNIK PERSADA", direktur: "YUSRI JUBIR", pemeriksa: "SUPRIADY IRAN" },
  { nama: "CV. LEON PRATAMA", direktur: "BEATRIX RENJAAN", pemeriksa: "" },
  { nama: "CV. MULTI KARYA JASA", direktur: "DIDIK PRIHERLIE", pemeriksa: "" },
  { nama: "PT. LAKSANA TEKHNIK MAKMUR", direktur: "H. SUWARNO", pemeriksa: "" },
  { nama: "PT. SATRYA REKSA BINAGUNA", direktur: "NICO TAMSTIL", pemeriksa: "" },
  { nama: "PT. MAKMUR MARINA METALINDO", direktur: "HENDRO HANDOJO", pemeriksa: "" },
  { nama: "PT. PIONEER", direktur: "HENDRIK NOVERO", pemeriksa: "" },
  { nama: "DIESEL TEKNIK", direktur: "KHRISMALA", pemeriksa: "" },
  { nama: "PT. TRI JAYA WARDANA", direktur: "ROSSY HERMAYANTI", pemeriksa: "" },
  { nama: "PT. KURNIA MANDALA INDONUSA", direktur: "CHANDRA KRISTIANTO", pemeriksa: "" },
  { nama: "PT. JOTUN INDONESIA", direktur: "NELSON", pemeriksa: "" },
  { nama: "PT. BARACUDA BINTANG SENTOSA", direktur: "JEVON ADNA TRISNAWAN", pemeriksa: "" },
  { nama: "PT. PASCADANA PURATAMA", direktur: "JUWAID ABDULLAH", pemeriksa: "" },
  { nama: "PT. BERKAT REHOBOT", direktur: "WELLY TITAH", pemeriksa: "" },
];

export const STAF_TEKNIK = ["Irsan Anugrah", "Supriady Iran"];
export const DEPT_HEAD = "Eryanto Sidabalok";

// nama kapal (dipakai sub-header tabel + BSTB per kapal). Reuse storloc dari material.
export const KAPAL_LIST = [
  "KMP. PORTLINK VIII", "KMP. BARONANG", "KMP. GORANGO", "KMP. BOBARA", "KMP. KERAPU II",
  "KMP. LOMPA", "KMP. ARIWANGAN", "KMP. PULAU SAGORI", "KMP. NGAFI", "KMP. MAMING",
  "KMP. TUNA", "KMP. KOLORAI", "KMP. LEMA",
];

// Database Matl Group (FORMAT SAP) — dari sheet DATABASE
export interface MatlGroup { kode: string; nama: string }
export const MATL_GROUP: MatlGroup[] = [
  { kode: "B01001", nama: "BBM - Kapal" },
  { kode: "B01002", nama: "BBM - Bungker" },
  { kode: "B01003", nama: "Pelumas/Oli Mesin" },
  { kode: "B01004", nama: "BB Kendaraan" },
  { kode: "B01005", nama: "Pelumas/Oli Hydrolik" },
  { kode: "B01006", nama: "Gemuk" },
  { kode: "B02001", nama: "Suku Cadang Kapal" },
  { kode: "B02002", nama: "SC Instalasi Faspel" },
  { kode: "B02003", nama: "SC Alat Faspel" },
  { kode: "B02004", nama: "SC Kendaraan" },
  { kode: "B02005", nama: "SC Peralatan Umum" },
  { kode: "B02006", nama: "SC Peralatan Deck" },
  { kode: "B02007", nama: "SC Mesin Induk" },
  { kode: "B02008", nama: "SC Mesin Bantu" },
  { kode: "B02009", nama: "SC Mesin Emrgncy Gen" },
  { kode: "B02010", nama: "SC Propulsion System" },
  { kode: "B02011", nama: "SC Kelistrikan Kapal" },
  { kode: "B02012", nama: "SC Genset Pelabuhan" },
  { kode: "B02013", nama: "Movable Bridge Pel" },
  { kode: "B02014", nama: "Hydrolik Sistem Pel" },
  { kode: "B02015", nama: "Timbangan Pelabuhan" },
  { kode: "B03001", nama: "Perlengkapan Bongkar" },
  { kode: "B03002", nama: "Mat. Galangan Kapal" },
  { kode: "B03003", nama: "Mat. Perbengkelan" },
  { kode: "B03004", nama: "Alat Navigasi Kapal" },
  { kode: "B03005", nama: "Alat Kes. Kapal" },
  { kode: "B03006", nama: "Sis. Kes. Kapal" },
  { kode: "B03007", nama: "Obat dan Alat Medis" },
  { kode: "B03008", nama: "Cat- kapal" },
  { kode: "B03009", nama: "Peralatan Umum-kapal" },
  { kode: "B03010", nama: "cat- pelabuhan" },
  { kode: "B03011", nama: "Peralatan Pelabuhan" },
  { kode: "B03012", nama: "Alat Perbengkelan" },
  { kode: "B03013", nama: "Surat&Sertifikat" },
  { kode: "B03014", nama: "Peralatan Interior" },
  { kode: "B03015", nama: "Material Interior" },
  { kode: "B03016", nama: "Alat Sensor Kapal" },
  { kode: "B04001", nama: "Pas Pelabuhan" },
  { kode: "B04002", nama: "Tiket Manual/Kertas" },
  { kode: "B04003", nama: "Alat Tulis Kantor" },
  { kode: "B04004", nama: "Benda Pos" },
  { kode: "B04005", nama: "Pencetakan Buku/Sert" },
  { kode: "B04006", nama: "Thermal Roll" },
  { kode: "B05001", nama: "Barang dagang" },
  { kode: "B05002", nama: "Makanan" },
  { kode: "B05003", nama: "Minuman" },
  { kode: "B06001", nama: "Server" },
  { kode: "B06002", nama: "Personal Computer" },
  { kode: "B06003", nama: "Finger Print Machine" },
  { kode: "B06004", nama: "License Software" },
  { kode: "B06005", nama: "Barierr Gate Complit" },
  { kode: "B06006", nama: "Laptop" },
  { kode: "B06007", nama: "Notebook" },
  { kode: "B06008", nama: "Scanner" },
  { kode: "B06009", nama: "Printer Laserjet" },
  { kode: "B06010", nama: "CCTV" },
  { kode: "B06011", nama: "Printer Dot Matriks" },
  { kode: "B06012", nama: "Printer Barcode" },
  { kode: "B06013", nama: "Infocus" },
  { kode: "B06014", nama: "Multimedia Task" },
  { kode: "B07001", nama: "Perlengkapan Kerja" },
  { kode: "B07002", nama: "Peralatan Kerja" },
  { kode: "B07003", nama: "Seragam Karyawan" },
  { kode: "B07004", nama: "BahanSeragam/Tesktil" },
  { kode: "B07005", nama: "Cat Bangunan" },
  { kode: "B07006", nama: "Mat.Prwtn Kendaraan" },
  { kode: "B07007", nama: "Perlengkapan RT" },
  { kode: "B07008", nama: "Mat.PerBangunanDinas" },
  { kode: "B07009", nama: "PerPrawatBngnnDinas" },
  { kode: "B07010", nama: "Perawatan Kendaraan" },
  { kode: "B07011", nama: "Per. Bangunan dinas" },
  { kode: "B07012", nama: "Sepatu Dinas" },
  { kode: "B07013", nama: "FireFightg Sys.Equip" },
  { kode: "B07014", nama: "Per.RuangRapat&Telco" },
  { kode: "B07015", nama: "Lighting&Elektrikal" },
  { kode: "B07016", nama: "Obat&Perlgkpn Medis" },
  { kode: "B07017", nama: "Konsumsi Rapat" },
  { kode: "B07018", nama: "Elc Device&Lifting" },
  { kode: "B07019", nama: "Genset Build Equip" },
  { kode: "B07020", nama: "Barang Konsumsi RT" },
  { kode: "B07021", nama: "Genset Building Sp." },
  { kode: "B07022", nama: "Ikat Pinggang" },
  { kode: "B07023", nama: "Topi Dinas" },
  { kode: "B07024", nama: "Topi Nahkoda" },
  { kode: "B07025", nama: "Bet&Emblem Perwira" },
  { kode: "B07026", nama: "Kendaraan Dinas" },
  { kode: "B08001", nama: "Spanduk" },
  { kode: "B08002", nama: "Flyer" },
  { kode: "B08003", nama: "Brosur" },
  { kode: "B08004", nama: "Advertising Media" },
  { kode: "B08005", nama: "Exhibition Media" },
  { kode: "B08006", nama: "Model/Miniatur dll" },
  { kode: "B08007", nama: "Merchandise" },
  { kode: "B09001", nama: "Bangunan Siap Jual" },
  { kode: "B09002", nama: "Air Bersih" },
  { kode: "B09003", nama: "Tiang Pancang" },
  { kode: "B09004", nama: "Material" },
  { kode: "B09005", nama: "Barang Jadi" },
  { kode: "B10001", nama: "Lahan Area Komersil" },
  { kode: "B10002", nama: "Lahan Area Kantor" },
  { kode: "B10003", nama: "Lahan Pel , Parkir &" },
  { kode: "B10004", nama: "Bangunan Komersil" },
  { kode: "B10005", nama: "Bangunan Gedung Kant" },
  { kode: "B10006", nama: "Bangunan Pel&Fas Pel" },
  { kode: "K01001", nama: "Kpl Penybrngan Baru" },
  { kode: "K02001", nama: "Kpl Penybrngan Bekas" },
  { kode: "J00001", nama: "Jasa Teknik" },
  { kode: "J00002", nama: "Jasa Asuransi" },
  { kode: "J00003", nama: "Jasa Kons & Profesi" },
  { kode: "J00004", nama: "Jasa Sewa" },
  { kode: "J00005", nama: "Jasa Sandar/Tambat" },
  { kode: "J00006", nama: "Jasa Kepil" },
  { kode: "J00007", nama: "Sewa Lahan/Bangunan" },
  { kode: "J00008", nama: "Jasa Pelayaran Kapal" },
  { kode: "J00009", nama: "Penginapan/hotel" },
  { kode: "J00010", nama: "Jasa Kepelabuhanan" },
  { kode: "J00011", nama: "Jasa Aktuaria" },
  { kode: "J00012", nama: "Pengembangan Sistem" },
  { kode: "J00013", nama: "Pemeliharaan & Rawat" },
  { kode: "J00014", nama: "Jasa Umum" },
  { kode: "J00015", nama: "Pelayanan Tng Kerja" },
  { kode: "J00016", nama: "Jasa Angkutan" },
  { kode: "J00017", nama: "Bongkar,Susun & Muat" },
  { kode: "J00018", nama: "Pemasaran Produk" },
  { kode: "J00019", nama: "Jasa Sistem & TI" },
  { kode: "J00020", nama: "Jasa Lainnya" },
];
